### PR TITLE
Fix error 500 on API creation event 

### PR DESCRIPTION
**Pull request by RignonNoel**
| Q                                                      | R
| ------------------------------------------ | -------------------------------------------
| Type of contribution ?                      | Fix
| Tickets (_issues_) concerned               | https://genielibre.com/issues/61

---

##### What have you changed ?
Add some check on event date during creation

##### How did you change it ?
 - Add a validator in the Event's serializer
 - Add some tests

##### Verification :

**PR standard**
 - [x] Branches naming convention: 
     - `prefix-snake_case_description`
     - ex: `enhancement-create_new_cell`
     - ex: `fix-pep8_standard_on_cell_model`
 - [x] Fill in this automatically generated PR template
 - [x] Do not include issue numbers in the PR title
 - [x] Include screenshots and animated GIFs in your pull request whenever possible

**Code standard**
 - [x] This Pull-Request fully meets the requirements defined in the issue
 - [x] Add or modify the attached tests
 - [x] Follow the Python Styleguide
 - [x] Document new code based on the Documentation Styleguide
 - [x] Use I18N functions when you add some text

### CODE REVIEW

**Comment by RignonNoel** [comment]
@yanicolivier We already have [an issue](https://genielibre.com/issues/6) for that.

**Comment by yanicolivier** [comment]
Okay ;)

**Comment by yanicolivier** [comment]
We need to add another validation to avoid the 500 on this IntegrityError : _The start date needs to be older than end date._  (see clean of Event models)

**Comment by RignonNoel** [comment]
@Jerome-Celle took a look on this PR and approved it in visio.

**Pull request merged**
