### PR TITLE
add script to fetch repository

### LINKED ISSUE #43: Install/Update script for developer
## Expected behaviour
We want to be able to just launch a script to init all the project in local.

## Current behavior
Actually we need to follow the `INSTALL.md` file.

## Potential solution
Add a script in `script` folder at the root of the repository.

### PR DESCRIPTION
**Pull request by RignonNoel**
| Q                                                      | R
| ------------------------------------------ | -------------------------------------------
| Type of contribution ?                      | Enhancement
| Tickets (_issues_) concerned               | fixed #43 

---

##### What have you changed ?
Allow user to init project or refresh it with just one commandline 

##### How did you change it ?
Add a bash script
You can call it from everywhere you want

Verification :
 -  [x] My branch name respect the standard defined in `CONTRIBUTING.md`
 -  [x] This Pull-Request fully meets the requirements defined in the issue
 -  [x] I added or modified the attached tests

### CODE REVIEW

**Comment by RignonNoel** [comment]
@DarkFranX 

`. env/bin/activate` is already done on line 13

I chose `fetch` because it's the same feeling for me when I use the Git command. I take some change and i bring back in my local setup. I've no possibility of conflict.

But i'm open to an other name, i think it's not the best name for the moment.

**Comment by DarkFranX** [comment]
It looks like the command on line 13 did not work on my side! After running the script, I am not in the virtualenv. 
For the name, I agree that we 'fetch' packages from the pipy repo, but we also migrate the DB. In the future, we may even do more things with that script! That is why I think we should give it a name like "setup.sh" or "local_setup.sh".

**Comment by RignonNoel** [comment]
@DarkFranX Do you have a return in your terminal about the line which don't works ?

**Comment by DarkFranX** [comment]
No, here is the full output:
https://framabin.org/?21a22968d20056e5#o+YVgG40XWtxZRH6lHXjRIsXnE/diBe2fQHutIO8f5Y=

I omitted a detail: I had to make the script executable. Should it be executable by default? Git can track file permissions

**Comment by RignonNoel** [comment]
It's strange because if the command `. env/bin/activate` doesn't works your migration can't work (you need to have the package Django). 

On your example it seem to work...
You prompt have no `(env)` prefix ?

```
Collecting pycodestyle==2.3.1 (from -r requirements-dev.txt (line 1))
  Using cached pycodestyle-2.3.1-py2.py3-none-any.whl
Installing collected packages: pycodestyle
Successfully installed pycodestyle-2.3.1
Operations to perform:
  Apply all migrations: admin, apiVolontaria, auth, authtoken, contenttypes, sessions, volunteer
Running migrations:
  No migrations to apply.
  Your models have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
```

**Comment by DarkFranX** [comment]
I suppose the script gets into the virtual environment but not the caller of the script. To be verified!

**Pull request closed without merging**
