### PR TITLE
fix password input and add profil inline

### LINKED ISSUE #130: Can't change the user's password from the admin panel
## Expected behaviour
I want to be able to change the user's password.

## Current behavior
I can only change the hash of the password.

## Potential solution
Find a way to overwrite the admin panel without unregister it.

Here is the problem in `ApiVolontaria/admin.py` :

```python
admin.site.unregister(User)
admin.site.register(User, UserAdmin)
```

## Step to reproduce (if it's a bug)

1. Go on the admin panel
2. Check a user or create a new one (you see a bad password input)
3. Go remove these two lines in `ApiVolontaria/admin.py`
4. Check a user or create a new one on the admin panel (it works)

## Your environment (if it's a bugs)

* Version used : Develop
* Version of softwares (python, firefox, chrome, ..) : --
* Operating System (Windows, Mac, Ubuntu, ArchLinux, ..): --

---

## Screenshots

screenshot-2018-2-16 change user django site admin

### PR DESCRIPTION
**Pull request by RignonNoel**
| Q                                                      | R
| ------------------------------------------ | -------------------------------------------
| Type of contribution ?                      | Fix
| Tickets (_issues_) concerned               | fixed #130 

---

##### What have you changed ?
 - Fix the user's password input in the admin panel
 - Add the profile in the user detail page of the admin panel

##### How did you change it ?
Refactor `ApiVolontaria/admin.py` to :
 - Ovrewrite default user's admin panel
 - Add an Inline
 - Add `mobile` and `phone` of profile in the user list

Verification :
 -  [x] My branch name respect the standard defined in `CONTRIBUTING.md`
 -  [x] This Pull-Request fully meets the requirements defined in the issue
 -  [ ] I added or modified the attached tests

---
## Screenshots

**New inline profile in the user's detail page:**
screenshot-2018-2-16 change user django site admin 1

---

**New listings of user in the admin panel:**
screenshot-2018-2-16 select user to change django site admin

---

**Fix password input:**
screenshot-2018-2-16 change user django site admin 2

### CODE REVIEW

**Comment by francisjeanneau** [comment]
I don't understand the part about the password. What related changes have you made? 

Also, one of the filter is named "By superuser status" but no columns exist showing the "superuser" status of users (only staff status).

**Comment by RignonNoel** [comment]
@francisjeanneau If you check the last screenshot of this PR you can see the password's input of Django (as at the beginning of the project). Without this PR it's a simple `CharField` who doesn't use the hashing method of Django.

You can see the current `CharField` who is a bug in the Issue referenced in this PR : #130

**Comment by RignonNoel** [comment]
> Also, one of the filter is named "By superuser status" but no columns exist showing the "superuser" status of users (only staff status).
> @francisjeanneau 

I've just check to be sure : We don't have the columns display but the filter on the right part of the page work well so you can filter by `is_superuser`.

**Comment by francisjeanneau** [comment]
The default admin page for User management includes a way to correctly change password. I suspect that this bug has been introduced by another PR. The default User page must be **incorrectly override**.

**Comment by RignonNoel** [comment]
@francisjeanneau It's exact. It's all the purpose of this PR : to correct it and overwrite the correctly the django admin panel.

**Comment by francisjeanneau** [comment]
I don't understand what is the change you made to correct the issue. Could you explain?

**Comment by RignonNoel** [comment]
Issue has been resolved by an other corrective PR.

**Pull request closed without merging**
