### PR TITLE
[WIP] Add a last_participation field to the Participation Serializer

### PR DESCRIPTION
**Pull request by yanicolivier**
| Q                                                      | R
| ------------------------------------------ | -------------------------------------------
| Type of contribution ?                      | [Enhancement]
| Tickets (_issues_) concerned               | [[250]](https://genielibre.com/issues/250)

---

Require the merge of API-Volontaria: [225](https://github.com/Volontaria/API-Volontaria/pull/225/)

##### What have you changed ?
Add a last_participation field to the Participation Serializer and split into ParticipationBasicSerializer and ParticipationAdminSerializer to show or not this field

##### Verification :

**PR standard**
 - [X] Branches naming convention: 
     - `prefix-snake_case_description`
     - ex: `enhancement-create_new_cell`
     - ex: `fix-pep8_standard_on_cell_model`
 - [X] Fill in this automatically generated PR template
 - [X] Do not include issue numbers in the PR title
 - [X] Include screenshots and animated GIFs in your pull request whenever possible

**Code standard**
 - [X] This Pull-Request fully meets the requirements defined in the issue
 - [X] Add or modify the attached tests
 - [X] Follow the Python Styleguide
 - [X] Document new code based on the Documentation Styleguide
 - [X] Use I18N functions when you add some text

### CODE REVIEW

**Comment by RignonNoel** [comment]
Why did you split into UserBasicSerializer and UserAdminSerializer to show or not this field ?

I just thinking that this field is not more confidential that all the other information from the User. So for me if we can acces the user, we should access the last_participation.

Can you explain your reflexion on this architecture ?

**Comment by yanicolivier** [comment]
@RignonNoel Yes sorry, it's because in the end UserAdminSerializer will make more sense when this PR will be merged: [225](https://github.com/Volontaria/API-Volontaria/pull/225/)

Adding the volunteer_note will need an admin Serializer
[https://github.com/Volontaria/API-Volontaria/pull/225/commits/317e41466fe9ddd19c3928e593049088ce00f357](https://github.com/Volontaria/API-Volontaria/pull/225/commits/317e41466fe9ddd19c3928e593049088ce00f357)

Do you want me to remove it here and it will be added to it when 225 is merged ?

**Comment by RignonNoel** [comment]
@yanicolivier As you prefer, we will need to discuss these points separatly. So ever we merge one PR before the other and close this one for the moment, ever we change this one and do the change in the other.

**Comment by yanicolivier** [comment]
@RignonNoel I have added a note in the description of this PR that it need the PR 225 to be merged.  Do you want me to close it for now (waiting for the other merge ?)

**Comment by RignonNoel** [comment]
@yanicolivier Just added a `[WIP]` tag in the title of this PR. When it will be ready do not forget to remove it and we will review it again :)

**Pull request closed without merging**
