### PR TITLE
Enhancement edit presence participation fields

### LINKED ISSUE #173: Allow to edit participation presence field
## Expected behaviour
I want the superuser to be able to edit presence field of each participations

## Current behavior
These fields are not available through the API

## Potential solution
1. Add a new serializer for superuser only
2. Change permission access

### PR DESCRIPTION
**Pull request by RignonNoel**
| Q                                                      | R
| ------------------------------------------ | -------------------------------------------
| Type of contribution ?                      | Enhancement
| Tickets (_issues_) concerned               | Fixed #173

---

##### What have you changed ?
 - Allow superuser to edit participations
 - Add new participation's fields in the API

##### How did you change it ?
1. Create a serializer for admin only
2. Change permission class to allow superuser to edit all participations
3. Update participation's serializer to display new fields

##### Verification :

**PR standard**
 - [x] Branches naming convention: 
     - `prefix-snake_case_description`
     - ex: `enhancement-create_new_cell`
     - ex: `fix-pep8_standard_on_cell_model`
 - [x] Fill in this automatically generated PR template
 - [x] Do not include issue numbers in the PR title
 - [x] Include screenshots and animated GIFs in your pull request whenever possible

**Code standard**
 - [x] This Pull-Request fully meets the requirements defined in the issue
 - [x] Add or modify the attached tests
 - [x] Follow the Python Styleguide
 - [x] Document new code based on the Documentation Styleguide
 - [x] Use I18N functions when you add some text

### CODE REVIEW

**Comment by RignonNoel** [comment]
> I'm not sure how to test this enhancement.
> 
> I have created a user that I give admin permissions but I have access to nothing. If I give the superuser permissions, he have access to all.

What did you mean by `admin permissions` ? Did you mean `user.is_staff=True` ?

To test you can :
1. Create a new superuser
2. List participations with the API (you will have all participations **with** new fields)
3. Get a specific participation with the API (you will have access **and** the new fields)
4. Update a specific participation with the API (you can do it and update these new fields)
5. Do the same thing with a user with his own participation (you don't have these fields but you can do the same actions)

**Comment by yanicolivier** [comment]
Thank you for the list, all is working fine but I'm not sure how to test the 5th case.
You mean get a token with a regular user (not admin) ?

**Comment by RignonNoel** [comment]
>Thank you for the list, all is working fine but I'm not sure how to test the 5th case.
You mean get a token with a regular user (not admin) ?
> @yanicolivier 

Exactly! A regular user with is own participation

**Comment by RignonNoel** [comment]
Approved by @yanicolivier on Slack

**Pull request merged**
