### PR TITLE
put error message in an array

### PR DESCRIPTION
**Pull request by RignonNoel**
| Q                                                      | R
| ------------------------------------------ | -------------------------------------------
| Type of contribution ?                      | Fix
| Tickets (_issues_) concerned               | None

---

##### What have you changed ?
Fix format of error in forgot password when user ask for a non existent username account

##### How did you change it ?
Fix error message by putting it in a standard array of message

##### Verification :

**PR standard**
 - [x] Branches naming convention: 
     - `prefix-snake_case_description`
     - ex: `enhancement-create_new_cell`
     - ex: `fix-pep8_standard_on_cell_model`
 - [x] Fill in this automatically generated PR template
 - [x] Do not include issue numbers in the PR title
 - [x] Include screenshots and animated GIFs in your pull request whenever possible

**Code standard**
 - [x] This Pull-Request fully meets the requirements defined in the issue
 - [x] Add or modify the attached tests
 - [x] Follow the Python Styleguide
 - [x] Document new code based on the Documentation Styleguide
 - [x] Use I18N functions when you add some text

### CODE REVIEW

**Comment by RignonNoel** [comment]
Custom message need to be translated in `.po` file. If some message are not translated we need to create a new PR to update all messages not translated in this version

**Comment by francisjeanneau** [comment]
@RignonNoel This is a good improvement, however I am wondering if we should use the specific field in this case:
```
'username': [
                     _("No account with this username.")
                 ],
```
This error is specific to the `username` field.

**Comment by RignonNoel** [comment]
@francisjeanneau You're right! I will change this :)

**Comment by RignonNoel** [comment]
@francisjeanneau Done ;)

**Pull request closed without merging**
